### ISSUE TITLE
Merge GFSK workflows

### ISSUE THREAD

**Issue by mariobaldini** [mariobaldini/gnuradio-gfsk-codec#1]
Analyze the work done in the previous GFSK workflows and merge them in a single/validaded flow. 
Cleanup old files after that.

As discussed, Gabriel's approach seems better and should be kept (?)

As of now, keep one flow for RX and another for TX.

**Comment by Theis159** [comment]
The best flow was chosen and it is in the root. For now on this should be the flow to be worked on. The legacy folder can be deleted.
