### ISSUE TITLE
gfsk_rx.py not working

### ISSUE THREAD

**Issue by mariobaldini** [mariobaldini/gnuradio-gfsk-codec#7]
Gabriel, consegui seguir o guia de instalação e rodar o gfsk_rx.py. 

Abre a UI, plot fft, etc... aparentemente funcional, mas na verdade não está: o fft está azul no máximo, o outro chart também, etc.. nao está pegando sinal real (nao mostra nem ruídos). 

Testei com o Ettus USRP B205mini-i. 

Dá uma revisada e deixa o .grc funcional. Dai exporto o .py aqui para testar novamente. 

@Theis159 Como proxima task deixa um .grc desses funcional com o ettus; mesmo que os parâmetros estejam fixos e sem as features q discutimos. Precisamos de um flow funcional para testar se o radio está enviando. 

Qdo vejo o debug da launchpad algumas linhas mostram: "Sending 0xAA, 0xBB..."

Eu queria pelo menos um GR_RX que possa abrir no PC e vai mostar "0xAABB..." no PC... para confirmar que o sinal foi de fato enviado e o PC recebeu. Depois vamos melhorando o flow com as demais features.

**Comment by mariobaldini** [comment]
Reiniciei a máquina; novo download do uhd cmd lá, e outras coisas... mas ainda não deu. 

https://hastebin.com/wexalomara.rb
https://hastebin.com/jawicumahu.rb

https://send.firefox.com/download/e1a5cf1e0b/#kCStkNO-Vch_AJoEZqy8YA

**Comment by Theis159** [comment]
Codigo funcional com o FunCube Dongle usando o comando:

python -u gfsk_rx.py -d "rtl_sdr=0" -s 2000000 -f 437500000 -b 1200 -w 25000 -g 1 -o "output.bin"

imagem: https://send.firefox.com/download/6e8f4add25/#XKu8YTu8DFFIc98Fbt84iA

Sobre o ettus:

- Verificar o significado do led (esta vermelho no momento)

- Verificar se "uhd=0" corresponde bem ao device

**Comment by Theis159** [comment]
FunCube Dongle e Ettus SDR funcionais.

## FunCube

'python -u gfsk_rx.py -d "rtl_sdr=0" -s 2000000 -f 437500000 -b 1200 -w 25000 -g 1 -o "output.bin" '

## Ettus SDR

'python -u gfsk_rx.py -d "uhd=0" -s 2000000 -f 437500000 -b 1200 -w 25000 -g 1 -o "output.bin" '
